name: Sync to Docker Hubd
on:
  workflow_dispatch:

jobs:
  sync-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Pull and push image
        run: |
          SOURCE_IMAGE="ghcr.io/hearchco/agent:latest"
          TARGET_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/hearchco-agent:latest"
          
          docker pull $SOURCE_IMAGE
          docker tag $SOURCE_IMAGE $TARGET_IMAGE
          docker push $TARGET_IMAGE

      - name: Pull and push image 2
        run: |
          SOURCE_IMAGEE="ghcr.io/hearchco/frontend:latest"
          TARGET_IMAGEE="${{ secrets.DOCKERHUB_USERNAME }}/hearchco-frontend:latest"
            
          docker pull $SOURCE_IMAGEE
          docker tag $SOURCE_IMAGEE $TARGET_IMAGEE
          docker push $TARGET_IMAGEE